-- Election Monitor — Supabase Schema
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)

-- Daily digests generated by LLM
create table daily_digests (
  id bigint generated always as identity primary key,
  generated_at timestamptz not null default now(),
  model text,
  changes jsonb not null default '[]'::jsonb,
  story jsonb not null default '{}'::jsonb,
  raw jsonb
);

create index idx_digests_date on daily_digests (generated_at desc);

-- Raw data snapshots for trend analysis
create table data_snapshots (
  id bigint generated always as identity primary key,
  snapshot_type text not null,
  generated_at timestamptz not null default now(),
  data jsonb not null
);

create index idx_snapshots_type_date on data_snapshots (snapshot_type, generated_at desc);

-- Enable Row Level Security
alter table daily_digests enable row level security;
alter table data_snapshots enable row level security;

-- Allow public read access (anon key)
create policy "Public read digests" on daily_digests
  for select using (true);

create policy "Public read snapshots" on data_snapshots
  for select using (true);

-- Allow insert via service_role key only (used by GitHub Actions)
create policy "Service insert digests" on daily_digests
  for insert with check (true);

create policy "Service insert snapshots" on data_snapshots
  for insert with check (true);

-- View: latest digest
create or replace view latest_digest as
  select * from daily_digests
  order by generated_at desc
  limit 1;

-- View: digest history (last 30 days)
create or replace view digest_history_30d as
  select
    id,
    generated_at,
    model,
    story->>'title' as story_title,
    jsonb_array_length(changes) as change_count,
    changes,
    story
  from daily_digests
  where generated_at > now() - interval '30 days'
  order by generated_at desc;
